### PR TITLE
Store user info in Mongo + GET /workspaces endpoint

### PR DESCRIPTION
**Pull request by jayleenli**
DO NOT MERGE YET - creating a Pull request for now to add comments on progress.

Merge only if 
- [x] Deploying works, no errors
- [x] Implements #21

### CODE REVIEW

**Comment by jayleenli** [comment]
Blocker: Trying to call AWS lambda functions from each other so that I can do a request to Google API to get the user's email and store it into MongoDB. Specifically wanting to call authorizer.handle from within handler.create_user does anyone know how to do this properly?

**Comment by jayleenli** [comment]
Or if I'm not understanding how the handler works let me know

**Comment by jayleenli** [comment]
Idea for what GET workspaces endpoint should return:
All workspace for the user

`{
            workspaces: [
              {
                       products: [
                             {
                                      //all of the stuff inside prouct
                              }
                        ]
              }

            ]
 }`

**Comment by btk5h** [comment]
LOOKS GOOD TO ME

**Pull request merged**
